services:
  backend-api:
    image: mi-backend-api:local
    env_file:
      - env/prod/.env
    restart: unless-stopped

  backend-db:
    image: postgres:15-alpine
    env_file:
      - env/prod/.env
    restart: unless-stopped

  web:
    image: proyecto1-web
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/certs:/etc/nginx/certs:ro
    ports:
      - "80:80"
      - "443:443"
    restart: unless-stopped
