name: CI Backend Docker

on:
  push:
    branches: [ci/docker-backend]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Build Docker image
        run: |
          docker build -f backend/Dockerfile -t backend-test:latest backend

      - name: Test backend healthcheck
        run: |
          docker run -d --name backend-test -p 3000:3000 backend-test:latest
          sleep 10
          curl -f http://localhost:3000/api/health
          docker rm -f backend-test
